# ref: https://docs.travis-ci.com/user/languages/python
language: python

services:
  - docker

python:
  - "3.6"

env:
  - NEO4J_VERSION="3.4.1" NEO4J_USERNAME="neo4j_test" NEO4J_PASSWORD="testpass"

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - bash .build/build_auth_string.sh $NEO4J_USERNAME:$NEO4J_PASSWORD > auth
  - mkdir -p neo4j-community-$NEO4J_VERSION/data/dbms
  - cp auth neo4j-community-$NEO4J_VERSION/data/dbms/
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # regenerate model and controller code from OpenAPI spec
  - docker pull openapitools/openapi-generator-cli
  - bash .build/codegen.sh

install:
  # command to install dependencies
  - pip install -r requirements.txt
  # command to install test dependencies
  - pip install -r test-requirements.txt
  # command to install coveralls
  - pip install python-coveralls
  # command to install package
  - pip install .

# command to run tests
script:
  - pytest --cov-config=.coveragerc --cov=synprov

after_success:
  - coveralls
