# ref: https://docs.travis-ci.com/user/languages/python
language: python

services:
  - docker

python:
  - "3.6"

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - bash .build/build_auth_string.sh $NEO4J_USERNAME:$NEO4J_PASSWORD > auth
  - mkdir -p neo4j-community-$NEO4J_VERSION/data/dbms
  - cp auth neo4j-community-$NEO4J_VERSION/data/dbms/
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # regenerate model and controller code from OpenAPI spec
  - docker pull openapitools/openapi-generator-cli
  - bash .build/codegen.sh

install:
  # command to install dependencies
  - pip install -r requirements.txt
  # command to install test dependencies
  - pip install -r test-requirements.txt
  # command to install coveralls
  - pip install python-coveralls
  # command to install package
  - pip install .

before_script:
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" = "develop" ]; then docker pull "${IMAGE_NAME}:develop" || true ; fi

# command to run tests
script:
  - pytest --cov-config=.coveragerc --cov=synprov
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" = "develop" ]; then docker build -f Dockerfile --pull --cache-from "${IMAGE_NAME}:develop" --tag "${IMAGE_NAME}" . ; fi

after_success:
  - coveralls

before_deploy:
  - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASS}" "${REGISTRY_SERVER}"
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:develop"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${git_sha}-develop"

deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:develop" && docker push "${IMAGE_NAME}:${git_sha}-develop"
    on:
      branch: develop
  - provider: codedeploy
    bucket: "phc-codedeploy-essentials-codedeploys3bucket-jumhvxvmnql0"
    key: deploy.zip
    bundle_type: zip
    access_key_id: "${CODEDEPLOY_ACCESS_KEY_ID}"
    secret_access_key: "${CODEDEPLOY_SECRET_ACCESS_KEY}"
    application: "phc-codedeploy-CodeDeployApplication-1JIG4ADRRDKT4"
    deployment_group: "phc-codedeploy-DeploymentGroup-3DWDGW9ASVEZ"
    region: "us-east-1"
    on:
      branch: develop