version: '3.2'

services:
  sbcp-neo4j:
    image: graphfoundation/ongdb:3.5
    container_name: sbcp-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - /tmp/neo4j/data:/var/lib/neo4j/data
      - /tmp/neo4j/logs:/logs

  sbcp-prov:
    image: sagebionetworks/prov-service
    command: python3 -m synprov
    container_name: sbcp-prov
    ports:
      - "8080:8080"
    environment:
      NEO4J_SCHEME: bolt
      NEO4J_HOST: sbcp-neo4j
      NEO4J_PORT: 7687
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      FLASK_HOST: "0.0.0.0"
    links:
      - sbcp-neo4j
