version: '3.2'

services:
  phccp-neo4j:
    image: docker.synapse.org/syn18489221/phccp-neo4j
    container_name: phccp-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - /tmp/neo4j/data:/var/lib/neo4j/data
      - /tmp/neo4j/logs:/logs

  phccp-prov:
    image: docker.synapse.org/syn18489221/prov-service:1.0.0-alpha.0
    command: python3 -m synprov
    container_name: phccp-prov
    ports:
      - "8080:8080"
    environment:
      NEO4J_SCHEME: bolt
      NEO4J_HOST: phccp-neo4j
      NEO4J_PORT: 7687
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      FLASK_HOST: "0.0.0.0"
    links:
      - phccp-neo4j
