# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov.models.agent import Agent
from synprov.models.reference import Reference
from synprov import util

from synprov.models.agent import Agent  # noqa: E501
from synprov.models.reference import Reference  # noqa: E501

class Activity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, used=None, generated=None, agents=None, created_by=None, etag=None, modified_on=None, modified_by=None, created_on=None, name=None, description=None):  # noqa: E501
        """Activity - a model defined in OpenAPI

        :param id: The id of this Activity.  # noqa: E501
        :type id: str
        :param used: The used of this Activity.  # noqa: E501
        :type used: List[Reference]
        :param generated: The generated of this Activity.  # noqa: E501
        :type generated: List[Reference]
        :param agents: The agents of this Activity.  # noqa: E501
        :type agents: List[Agent]
        :param created_by: The created_by of this Activity.  # noqa: E501
        :type created_by: str
        :param etag: The etag of this Activity.  # noqa: E501
        :type etag: str
        :param modified_on: The modified_on of this Activity.  # noqa: E501
        :type modified_on: datetime
        :param modified_by: The modified_by of this Activity.  # noqa: E501
        :type modified_by: str
        :param created_on: The created_on of this Activity.  # noqa: E501
        :type created_on: datetime
        :param name: The name of this Activity.  # noqa: E501
        :type name: str
        :param description: The description of this Activity.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'id': str,
            'used': List[Reference],
            'generated': List[Reference],
            'agents': List[Agent],
            'created_by': str,
            'etag': str,
            'modified_on': datetime,
            'modified_by': str,
            'created_on': datetime,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'used': 'used',
            'generated': 'generated',
            'agents': 'agents',
            'created_by': 'createdBy',
            'etag': 'etag',
            'modified_on': 'modifiedOn',
            'modified_by': 'modifiedBy',
            'created_on': 'createdOn',
            'name': 'name',
            'description': 'description'
        }

        self._id = id
        self._used = used
        self._generated = generated
        self._agents = agents
        self._created_by = created_by
        self._etag = etag
        self._modified_on = modified_on
        self._modified_by = modified_by
        self._created_on = created_on
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Activity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Activity of this Activity.  # noqa: E501
        :rtype: Activity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Activity.


        :return: The id of this Activity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Activity.


        :param id: The id of this Activity.
        :type id: str
        """

        self._id = id

    @property
    def used(self):
        """Gets the used of this Activity.


        :return: The used of this Activity.
        :rtype: List[Reference]
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this Activity.


        :param used: The used of this Activity.
        :type used: List[Reference]
        """

        self._used = used

    @property
    def generated(self):
        """Gets the generated of this Activity.


        :return: The generated of this Activity.
        :rtype: List[Reference]
        """
        return self._generated

    @generated.setter
    def generated(self, generated):
        """Sets the generated of this Activity.


        :param generated: The generated of this Activity.
        :type generated: List[Reference]
        """

        self._generated = generated

    @property
    def agents(self):
        """Gets the agents of this Activity.


        :return: The agents of this Activity.
        :rtype: List[Agent]
        """
        return self._agents

    @agents.setter
    def agents(self, agents):
        """Sets the agents of this Activity.


        :param agents: The agents of this Activity.
        :type agents: List[Agent]
        """

        self._agents = agents

    @property
    def created_by(self):
        """Gets the created_by of this Activity.


        :return: The created_by of this Activity.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Activity.


        :param created_by: The created_by of this Activity.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def etag(self):
        """Gets the etag of this Activity.


        :return: The etag of this Activity.
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this Activity.


        :param etag: The etag of this Activity.
        :type etag: str
        """

        self._etag = etag

    @property
    def modified_on(self):
        """Gets the modified_on of this Activity.


        :return: The modified_on of this Activity.
        :rtype: datetime
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this Activity.


        :param modified_on: The modified_on of this Activity.
        :type modified_on: datetime
        """

        self._modified_on = modified_on

    @property
    def modified_by(self):
        """Gets the modified_by of this Activity.


        :return: The modified_by of this Activity.
        :rtype: str
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this Activity.


        :param modified_by: The modified_by of this Activity.
        :type modified_by: str
        """

        self._modified_by = modified_by

    @property
    def created_on(self):
        """Gets the created_on of this Activity.


        :return: The created_on of this Activity.
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Activity.


        :param created_on: The created_on of this Activity.
        :type created_on: datetime
        """

        self._created_on = created_on

    @property
    def name(self):
        """Gets the name of this Activity.


        :return: The name of this Activity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Activity.


        :param name: The name of this Activity.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Activity.


        :return: The description of this Activity.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Activity.


        :param description: The description of this Activity.
        :type description: str
        """

        self._description = description
