# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov import util


class Activity1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _class=None):  # noqa: E501
        """Activity1 - a model defined in OpenAPI

        :param _class: The _class of this Activity1.  # noqa: E501
        :type _class: str
        """
        self.openapi_types = {
            '_class': str
        }

        self.attribute_map = {
            '_class': 'class'
        }

        self.__class = _class

    @classmethod
    def from_dict(cls, dikt) -> 'Activity1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Activity_1 of this Activity1.  # noqa: E501
        :rtype: Activity1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _class(self):
        """Gets the _class of this Activity1.


        :return: The _class of this Activity1.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """Sets the _class of this Activity1.


        :param _class: The _class of this Activity1.
        :type _class: str
        """

        self.__class = _class
