# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov import util


class Agent1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None):  # noqa: E501
        """Agent1 - a model defined in OpenAPI

        :param user_id: The user_id of this Agent1.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'user_id': str
        }

        self.attribute_map = {
            'user_id': 'userId'
        }

        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Agent1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Agent_1 of this Agent1.  # noqa: E501
        :rtype: Agent1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this Agent1.


        :return: The user_id of this Agent1.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Agent1.


        :param user_id: The user_id of this Agent1.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
