# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov import util


class D3Node(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, labels=None, properties=None):  # noqa: E501
        """D3Node - a model defined in OpenAPI

        :param id: The id of this D3Node.  # noqa: E501
        :type id: str
        :param labels: The labels of this D3Node.  # noqa: E501
        :type labels: List[str]
        :param properties: The properties of this D3Node.  # noqa: E501
        :type properties: object
        """
        self.openapi_types = {
            'id': str,
            'labels': List[str],
            'properties': object
        }

        self.attribute_map = {
            'id': 'id',
            'labels': 'labels',
            'properties': 'properties'
        }

        self._id = id
        self._labels = labels
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'D3Node':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The D3Node of this D3Node.  # noqa: E501
        :rtype: D3Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this D3Node.


        :return: The id of this D3Node.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this D3Node.


        :param id: The id of this D3Node.
        :type id: str
        """

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this D3Node.


        :return: The labels of this D3Node.
        :rtype: List[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this D3Node.


        :param labels: The labels of this D3Node.
        :type labels: List[str]
        """

        self._labels = labels

    @property
    def properties(self):
        """Gets the properties of this D3Node.


        :return: The properties of this D3Node.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this D3Node.


        :param properties: The properties of this D3Node.
        :type properties: object
        """

        self._properties = properties
