# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov.models.neo4j_graph_graph import Neo4jGraphGraph
from synprov import util


class Neo4jGraphData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, graph=None):  # noqa: E501
        """Neo4jGraphData - a model defined in OpenAPI

        :param graph: The graph of this Neo4jGraphData.  # noqa: E501
        :type graph: Neo4jGraphGraph
        """
        self.openapi_types = {
            'graph': Neo4jGraphGraph
        }

        self.attribute_map = {
            'graph': 'graph'
        }

        self._graph = graph

    @classmethod
    def from_dict(cls, dikt) -> 'Neo4jGraphData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Neo4jGraph_data of this Neo4jGraphData.  # noqa: E501
        :rtype: Neo4jGraphData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def graph(self):
        """Gets the graph of this Neo4jGraphData.


        :return: The graph of this Neo4jGraphData.
        :rtype: Neo4jGraphGraph
        """
        return self._graph

    @graph.setter
    def graph(self, graph):
        """Sets the graph of this Neo4jGraphData.


        :param graph: The graph of this Neo4jGraphData.
        :type graph: Neo4jGraphGraph
        """

        self._graph = graph
