# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov.models.neo4j_graph_results import Neo4jGraphResults
from synprov import util


class Neo4jGraph(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, results=None):  # noqa: E501
        """Neo4jGraph - a model defined in OpenAPI

        :param results: The results of this Neo4jGraph.  # noqa: E501
        :type results: List[Neo4jGraphResults]
        """
        self.openapi_types = {
            'results': List[Neo4jGraphResults]
        }

        self.attribute_map = {
            'results': 'results'
        }

        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'Neo4jGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Neo4jGraph of this Neo4jGraph.  # noqa: E501
        :rtype: Neo4jGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self):
        """Gets the results of this Neo4jGraph.


        :return: The results of this Neo4jGraph.
        :rtype: List[Neo4jGraphResults]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Neo4jGraph.


        :param results: The results of this Neo4jGraph.
        :type results: List[Neo4jGraphResults]
        """

        self._results = results
