# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from synprov.models.base_model_ import Model
from synprov import util


class Reference(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, target_version_number=None, target_id=None, role=None):  # noqa: E501
        """Reference - a model defined in OpenAPI

        :param target_version_number: The target_version_number of this Reference.  # noqa: E501
        :type target_version_number: int
        :param target_id: The target_id of this Reference.  # noqa: E501
        :type target_id: str
        :param role: The role of this Reference.  # noqa: E501
        :type role: str
        """
        self.openapi_types = {
            'target_version_number': int,
            'target_id': str,
            'role': str
        }

        self.attribute_map = {
            'target_version_number': 'targetVersionNumber',
            'target_id': 'targetId',
            'role': 'role'
        }

        self._target_version_number = target_version_number
        self._target_id = target_id
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'Reference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reference of this Reference.  # noqa: E501
        :rtype: Reference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_version_number(self):
        """Gets the target_version_number of this Reference.


        :return: The target_version_number of this Reference.
        :rtype: int
        """
        return self._target_version_number

    @target_version_number.setter
    def target_version_number(self, target_version_number):
        """Sets the target_version_number of this Reference.


        :param target_version_number: The target_version_number of this Reference.
        :type target_version_number: int
        """

        self._target_version_number = target_version_number

    @property
    def target_id(self):
        """Gets the target_id of this Reference.


        :return: The target_id of this Reference.
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this Reference.


        :param target_id: The target_id of this Reference.
        :type target_id: str
        """

        self._target_id = target_id

    @property
    def role(self):
        """Gets the role of this Reference.


        :return: The role of this Reference.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Reference.


        :param role: The role of this Reference.
        :type role: str
        """

        self._role = role
